### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hrbrmstr** [wch/harbor#8]
- [ ] Update README
- [ ] Remove `analogsea` as a dependency
- [ ] Go through the various "cloud" R pkgs and see which ones use an API for container ops and which ones just use `ssh`. The ones that use `ssh` should prbly just use the new built-in `ssh` host object.
- [ ] Make an example S3 host class for an API example in ^^
- [ ] Tests

**Comment by MarkEdmondson1234** [comment]
re:
> Go through the various "cloud" R pkgs and see which ones use an API for container ops and which ones just use ssh. 

I think I'm of the `ssh` method, I put my specific to `harbor` functions in this file: https://github.com/cloudyr/googleComputeEngineR/blob/master/R/harbor_gce.R which includes a `gce_instance` method for `docker_cmd` and a function to build docker containers on the host from a local `Dockerfile`.

**Comment by MarkEdmondson1234** [comment]
@hrbrmstr Are you going to be moving to use the Docker API https://docs.docker.com/engine/api/ ?  That will be great to solve some issues I have when Windows users can't authenticate in SSH

**Comment by hrbrmstr** [comment]
I've been considering adding it as an option. I confess to not using the
Docker Engine API ever (cmdline has been sufficient for me). Is it always
enabled, now? IIRC the "socket" is always around but the HTTP API requires
explicit enabling (that's just a guess from memory tho)

**Comment by MarkEdmondson1234** [comment]
@hrbrmstr it sounds like you know more than I, I just found it else I may have tried to tackle it before. Even if just the "docker exec" commands could be enabled, it will solve a lot of compatibility problems for me. I could take a look at it if it doesn't interfere with what you are doing?
